"""Emit a data/npc_servants.json record for an enemy/boss servant id from Atlas.

Usage:
    python scripts/fetch_npc.py 9935500 9935400 ...

Prints the JSON record(s) so you can paste them into data/npc_servants.json (which is
hand-curated, NOT regenerated by sync_atlas.py). These units appear in /guessservant
only -- the loader forces `figure` empty and flags `npc`, so the shadow and voice
games skip them.

Look the id up first (never guess it), e.g. via the Atlas search:
    https://api.atlasacademy.io/basic/NA/servant/search?name=Goetia&lang=en

Review each record before committing: Atlas class names come through raw (e.g.
"beastI"); prettify `className` by hand (e.g. "Beast I") since it is shown to players.
"""
from __future__ import annotations

import json
import sys
import urllib.request

REGION = "NA"


def fetch(servant_id: int) -> dict:
    url = (
        f"https://api.atlasacademy.io/nice/{REGION}/servant/{servant_id}"
        "?lang=en&lore=true"
    )
    with urllib.request.urlopen(url) as resp:
        s = json.load(resp)
    extra = s.get("extraAssets", {})
    art = {
        str(k): v
        for k, v in extra.get("charaGraph", {}).get("ascension", {}).items()
        if v
    }
    faces = extra.get("faces", {}).get("ascension", {})
    face = faces.get("0") or faces.get("1") or next(iter(faces.values()), None)
    return {
        "id": s["id"],
        "name": s["name"],
        "className": s.get("className", ""),  # prettify by hand, e.g. "Beast I"
        "rarity": s.get("rarity", 0),
        "gender": s.get("gender", ""),
        "attribute": s.get("attribute", ""),
        "traits": [t["name"] for t in s.get("traits", []) if t.get("name")],
        "art": art,
        "figure": {},  # art game only
        "face": face,
        "cv": ((s.get("profile") or {}).get("cv") or "").strip() or None,
        "npc": True,
    }


def main() -> int:
    ids = [int(a) for a in sys.argv[1:]]
    if not ids:
        print(__doc__)
        return 1
    records = [fetch(i) for i in ids]
    print(json.dumps(records, ensure_ascii=False, indent=2))
    if any(not r["art"] for r in records):
        print(
            "\nWARNING: a record has no charaGraph.ascension art -- it would be dropped "
            "at load. That boss keeps its art elsewhere (e.g. charaGraph.story); pull "
            "the URL by hand or skip it.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
